name: Sync Plugins to CMS
on:
  push:
    branches: [main]
    tags: ['*']
  # TODO: remove pull_request section once this is ready for production, i.e. when this is about to be merged into the repo
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sync-to-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          cache: 'npm'
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Sync plugins to CMS
        env:
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
        run: npx tsx bin/sync_plugins_to_cms.js
